### ISSUE TITLE
CODEOWNERS groups lack write permissions

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-template-repo-java#14]
The @NASA-PDS/pds-software-committers lacks write perms to the repo so CODEOWNERS isn't doing anything for us.

See #13 for demonstration.

**Comment by nutjob4life** [comment]
Changed "Read" → "Write" for @NASA-PDS/pds-software-committers on this repository
![Screen Shot 2021-09-01 at 5 44 13 PM](https://user-images.githubusercontent.com/814813/131755095-d21bd09a-9ae7-48f2-afc7-2a60582ec03e.png)
